# Generated by Django 2.0.1 on 2018-01-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Plastos Extra',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('additional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.AdditionalFood')),
            ],
            options={
                'verbose_name': 'Opciones del Menú',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_menu', models.DateField(auto_now=True)),
                ('foods', models.ManyToManyField(to='menu.Food')),
            ],
            options={
                'verbose_name': 'Menú',
            },
        ),
    ]
