# Generated by Django 2.0.1 on 2018-01-24 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comida Extra',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Opciones del Menú',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date_menu', models.DateField(auto_now_add=True)),
                ('foods', models.ManyToManyField(to='menu.Food')),
            ],
            options={
                'verbose_name': 'Menú',
                'ordering': ['-date_menu'],
            },
        ),
    ]
