# Generated by Django 2.0.1 on 2018-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_additionalfood_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfood',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
